### ISSUE TITLE
Local interface/ip

### ISSUE THREAD

**Issue by martinthomson** [mozilla/mtu#15]
The interface uses a remote address only.  `UdpSocket::bind` takes a local address, which is presently unspecified.  A more general approach would be to specify the *local* address in addition to the *remote* address.

**Comment by larseggert** [comment]
Good idea. If a local address is passed in, that would preclude the need to connect the socket, since the binding already establishes which interface will be used.

Do you see this as one call, where either local or remote can be unspecified? Or two calls?

**Comment by martinthomson** [comment]
¯\\\_(ツ)\_/¯

It's a hard one.  You could make the interface take a new enum type something like this:

```rust
enum SocketAddresses {
  Local(SocketAddr),
  Remote(SocketAddr),
  Both((SocketAddr, SocketAddr)),
}

impl From<(SocketAddr, SocketAddr)> for SocketAddresses { ... }
impl From<(Option<SocketAddr>, SocketAddr)> for SocketAddresses { ... }
impl From<(SocketAddr, Option<SocketAddr>)> for SocketAddresses { ... }
// I don't know if UdpSocket::connect works with a remote port of 0, but you could try each of these...
impl From<(IpAddr, IpAddr)> for SocketAddresses { ... } // Uses port = 0
impl From<(IpAddr, Option<IpAddr>)> for SocketAddresses { ... }
impl From<(Option<IpAddr>, IpAddr)> for SocketAddresses { ... }

pub fn interface_mtu<A>(addrs: A)
  where SocketAddresses: From<A> { ... }
```
