### ISSUE TITLE
Suggest splitting the workflow in different jobs

### ISSUE THREAD

**Issue by djc** [mozilla/mtu#19]
CI would give feedback a lot faster if you split it into multiple jobs. Some things don't need to be run on every cell in the build matrix, and some jobs can give feedback much faster, and Actions will parallelize for you.

(See [Quinn](https://github.com/quinn-rs/quinn/blob/main/.github/workflows/rust.yml) for an example.)

**Comment by larseggert** [comment]
The CI pipeline for this feels fast enough, esp. compared to neqo. Would this really get us much?
