### ISSUE TITLE
Support BSDs

### ISSUE THREAD

**Issue by larseggert** [mozilla/mtu#20]
The macOS code path should roughly work on the BSDs, too. It would be good to confirm that, maybe by adding CI support based on https://github.com/vmactions for them and then work out any kinks.

**Comment by miguelcsx** [comment]
# `interface_and_mtu_impl` Errors on BSD During CI Execution

I have been working on extending the macOS code path to BSD systems, using the [vmactions](https://github.com/vmactions) GitHub Actions to add CI support for these systems. To achieve this, I created a separate CI job specifically for BSD, following a similar build and test setup used in other CI/CD. The CI/CD implementation can be found in my fork in [this commit](https://github.com/miguelcsx/mtu/commit/dfb6490fe98a72fdb11df09f18aace70288fc61a)

However, during the build, I encountered some type mismatch errors in the `interface_and_mtu_impl` function. These errors occur without any modifications to the `lib.rs` file — the only change was adding the BSD CI job.

The errors I received were:

```rust

error[E0308]: mismatched types
   --> src/lib.rs:99:5
   |
76 | pub fn interface_and_mtu<A>(addrs: A) -> Result<(String, usize), Error>
   | -------------------------------------- expected `Result<(String, usize), Error>` because of return type
99 | interface_and_mtu_impl(&socket)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(String, usize), Error>`, found `Result<usize, Error>`
```

The function is expecting a result with a tuple `(String, usize)`, but the `interface_and_mtu_impl` is returning `Result<usize, Error>` instead.
### Steps Taken:

- Added a separate BSD CI job using `vmactions` ([commit in fork](https://github.com/miguelcsx/mtu/commit/dfb6490fe98a72fdb11df09f18aace70288fc61a)).
- Attempted to build the project locally on a FreeBSD virtual machine using Cargo, and encountered the same errors.
- No changes were made to the codebase (specifically `lib.rs`), only the CI configuration.
- Errors occur in the `interface_and_mtu_impl` function.

**Comment by mxinden** [comment]
Thanks for the report. I will open a pull request in a couple of minutes @miguelcsx.

**Comment by mxinden** [comment]
@miguelcsx https://github.com/mozilla/mtu/pull/21 should resolve the issues you were seeing. Mind testing it out?

**Comment by miguelcsx** [comment]
> @miguelcsx #21 should resolve the issues you were seeing. Mind testing it out?

@mxinden I tested it on a freebsd virtual machine and it runs without any errors, it seems to solve the error presented

**Comment by mxinden** [comment]
Great. Let us know if you need any more help. Thanks for the work @miguelcsx!
